from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import (
    BigInteger,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column

from prism.db.base import Base


class Insight(Base):
    """AI-generated insight about a property's analytics.

    The narrative (`title`, `summary`) is generated by Claude. The numbers in
    `supporting_data` are computed by the detector layer (SQL/pandas) — Claude
    never recomputes them.
    """

    __tablename__ = "insights"
    __table_args__ = (
        UniqueConstraint(
            "property_id", "kind", "period_start", "period_end",
            name="uq_insights_property_kind_period",
        ),
        Index("ix_insights_property_status_detected", "property_id", "status", "detected_at"),
        Index("ix_insights_property_kind", "property_id", "kind"),
    )

    property_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("properties.id", ondelete="CASCADE"), nullable=False,
    )
    kind: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    supporting_data: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="new", nullable=False)
    claude_model_used: Mapped[str | None] = mapped_column(String(100), nullable=True)
    claude_input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    claude_output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)


class ClaudeCallLog(Base):
    """Every Claude API call is logged here — required by project policy."""

    __tablename__ = "claude_call_logs"
    __table_args__ = (
        Index("ix_claude_call_logs_tenant_purpose_created", "tenant_id", "purpose", "created_at"),
    )

    tenant_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False,
    )
    property_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("properties.id", ondelete="SET NULL"), nullable=True,
    )
    purpose: Mapped[str] = mapped_column(String(100), nullable=False)
    model: Mapped[str] = mapped_column(String(100), nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    latency_ms: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
